name: Build Wine
on:
  push:
permissions:
  contents: read
env:
  WINE_VERSION: 9.2
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 'Setup environment'
      run: |
        echo "WINE_ARCHIVE=${{ github.workspace }}/wine-vinegarhq-build-${{ env.WINE_VERSION }}.tar.xz" >> $GITHUB_ENV
        echo "WINE_PREFIX=${{ github.workspace }}/wine-vinegarhq-build-${{ env.WINE_VERSION }}" >> $GITHUB_ENV
        echo "PATH=/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH" >> $GITHUB_ENV
        sudo dpkg --add-architecture i386
        sudo apt update -y
        sudo apt install \
          lib32z1 \
          git \
          build-essential \
          curl \
          gcc-multilib \
          g++-multilib \
          flex \
          bison \
          libasound2-dev \
          libpulse-dev \
          libdbus-1-dev \
          libfontconfig-dev \
          libfreetype-dev \
          libfreetype6-dev:i386 \
          libgl-dev \
          libunwind-dev \
          libx11-dev \
          libx11-dev:i386 \
          libxcomposite-dev \
          libxcomposite-dev:i386 \
          libxcursor-dev \
          libxfixes-dev \
          libxfixes-dev:i386 \
          libxi-dev \
          libxrandr-dev \
          libxrandr-dev:i386 \
          libxrender-dev \
          libxrender-dev:i386 \
          libxext-dev \
          libgstreamer1.0-dev \
          libgstreamer-plugins-base1.0-dev \
          libosmesa6-dev \
          libudev-dev \
          libvulkan-dev \
          libkrb5-dev \
          libusb-1.0-0-dev \
          libv4l-dev \
          libxkbcommon-dev \
          libxkbregistry-dev \
          libwayland-dev \
          libxxf86vm-dev \
          libxinerama-dev \
          nvidia-opencl-dev \
          libpcap-dev \
          libpcsclite-dev \
          libsane-dev \
          libgettextpo-dev \
          libgnutls28-dev \
          libgphoto2-dev \
          libsdl2-dev \
          libcapi20-dev \
          libcups2-dev \
          ccache

    - name: 'Configure ccache'
      uses: hendrikmuhs/ccache-action@v1.2

    - name: 'Checkout Repository'
      uses: actions/checkout@v3

    - name: 'Fetch Wine'
      run: |
        git clone https://gitlab.winehq.org/wine/wine.git --depth 1 \
          --branch wine-${{ env.WINE_VERSION }}
        mkdir -p wine/wine-64
        mkdir -p wine/wine-32

    - name: 'Apply Wine Staging patchset'
      run: |
        git clone https://gitlab.winehq.org/wine/wine-staging.git --depth 1 \
          --branch v${{ env.WINE_VERSION }}
        wine-staging/staging/patchinstall.py --destdir=wine --all
    - name: 'Apply local patches'
      working-directory: wine
      run: |
        for p in ../*.patch; do
          echo $p
          patch -p1 < $p
        done

    - name: 'Configure Wine 64'
      working-directory: wine/wine-64
      run: |
        mkdir -p ${{ env.WINE_PREFIX }}
        ../configure \
          CC='ccache gcc' \
          CFLAGS='-O3 -pipe -march=x86-64-v2 -mpclmul -mavx' \
          CXXFLAGS='-O3 -pipe -march=x86-64-v2 -mpclmul -mavx' \
          CROSSCFLAGS='-O3 -pipe -march=x86-64-v2 -mpclmul -mavx' \
          --prefix=${{ env.WINE_PREFIX }} \
          --enable-win64 \
          --disable-win16 \
          --disable-tests \
          --with-alsa \
          --with-pulse \
          --with-dbus \
          --with-fontconfig \
          --with-freetype \
          --with-opengl \
          --with-wayland \
          --with-x \
          --with-xcomposite \
          --with-xfixes \
          --with-xinput2 \
          --with-xrandr \
          --with-xrender \
          --with-gstreamer \
          --with-vulkan \
          --with-krb5 \
          --with-usb \
          --with-v4l2
    - name: 'Configure Wine 32'
      working-directory: wine/wine-32
      run: |
        mkdir -p ${{ env.WINE_PREFIX }}
        ../configure \
          CC='ccache gcc' \
          CFLAGS='-O3 -pipe -march=native -mpclmul -mavx' \
          CXXFLAGS='-O3 -pipe -march=native -mpclmul -mavx' \
          CROSSCFLAGS='-O3 -pipe -march=native -mpclmul -mavx' \
          --prefix=${{ env.WINE_PREFIX }} \
          --with-wine64=../wine-64 \
          --disable-win16 \
          --disable-tests \
          --with-alsa \
          --with-pulse \
          --with-dbus \
          --with-fontconfig \
          --with-freetype \
          --with-opengl \
          --with-wayland \
          --with-x \
          --with-xcomposite \
          --with-xfixes \
          --with-xinput2 \
          --with-xrandr \
          --with-xrender \
          --with-gstreamer \
          --with-vulkan \
          --with-krb5 \
          --with-usb \
          --with-v4l2

    - name: 'Build Wine 64'
      working-directory: wine/wine-64
      run: make -j$(($(nproc) + 1))
    - name: 'Build Wine 32'
      working-directory: wine/wine-32
      run: make -j$(($(nproc) + 1))
    - name: 'Install Wine 64'
      working-directory: wine/wine-64
      run: make install LDCONFIG=/bin/true UPDATE_DESKTOP_DATABASE=/bin/true
    - name: 'Install Wine 32'
      working-directory: wine/wine-32
      run: make install LDCONFIG=/bin/true UPDATE_DESKTOP_DATABASE=/bin/true

    - name: 'Strip Wine'
      working-directory: ${{ env.WINE_PREFIX }}
      run: |
        x86_64-w64-mingw32-strip --strip-unneeded lib/wine/x86_64-windows/*.dll

    - name: Make artifacts
      run: |
        cd $(dirname ${{ env.WINE_PREFIX }})
        XZ_OPT=-9 tar -Jcf ${{ env.WINE_ARCHIVE }} $(basename ${{ env.WINE_PREFIX }})

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: wine-vinegarhq-build-${{ env.WINE_VERSION }}
        path: ${{ env.WINE_ARCHIVE }}
